### ISSUE TITLE
socket.timeout Error Catching

### ISSUE THREAD

**Issue by jacob-roth** [veox/python3-krakenex#46]
### Versions

```
OS: 10.12.6      
Python: 3.5
krakenex: 1.0.0a1
```

### What are you trying to achieve?
Trying to catch a timeout error.

``` python
# code sample
except socket.timeout as e:
                print("Kraken Socket Timeout Error")
                print(e)
```

### What do you expect to happen?
Expected error to be caught. I believe this is a naive error on my part -- just looking for the proper way to handle.

### What happens instead?
I receive the below error message.

``` python
# error message
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    except socket.timeout as e:
NameError: name 'socket' is not defined
```

**Comment by veox** [comment]
Did you `import socket`?

If so, please post a minimal example to reproduce.

**Comment by veox** [comment]
You were probably trying to catch for this:

``` python
Traceback (most recent call last):
  File "./print-available-balances.py", line 20, in <module>
    balance = k.query_private('Balance')
  File "/home/veox/.local/lib/python3.6/site-packages/krakenex/api.py", line 206, in query_private
    return self._query(urlpath, req, conn, headers)
  File "/home/veox/.local/lib/python3.6/site-packages/krakenex/api.py", line 149, in _query
    ret = conn._request(url, req, headers)
  File "/home/veox/.local/lib/python3.6/site-packages/krakenex/connection.py", line 90, in _request
    response = self.conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1002, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 625, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

**Comment by warmpiyro** [comment]
#Hope this helps!!!
import socket
from socket import *
#--version Python 3.6.4
try:
     #yourcode 
except   timeout: 
     #print error
