### ISSUE TITLE
timing out on Assets query

### ISSUE THREAD

**Issue by Newbrict** [veox/python3-krakenex#69]
### Versions

```
OS:       Win 10 Pro version 1703 build 15063.674
Python:   Python 3.6.2
krakenex:  krakenex==1.0.0
```

### What are you trying to achieve?
k.query_public('Assets')

``` python
# code sample
k.query_public('Assets')
```

### What do you expect to happen?
returns the api output

### What happens instead?
I had a timeout, this doesn't happen all the time, but does happen. is this an exception i should be catching?

``` python
# error message
Traceback (most recent call last):
  File "data_collector.py", line 126, in <module>
    error = collectKrakenBalances()
  File "data_collector.py", line 59, in collectKrakenBalances
    asset_info = k.query_public('Assets')
  File "/root/cipher/api/ENV/lib/python3.5/site-packages/krakenex/api.py", line 168, in query_public
    return self._query(urlpath, req, conn)
  File "/root/cipher/api/ENV/lib/python3.5/site-packages/krakenex/api.py", line 148, in _query
    ret = conn._request(url, req, headers)
  File "/root/cipher/api/ENV/lib/python3.5/site-packages/krakenex/connection.py", line 91, in _request
    response = self.conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

**Comment by veox** [comment]
You _could_, but it's essentially Kraken's late months' inability to handle request load.

Since this is a public query (no private data involved), it should be safe to just wait and repeat the query.

-----

Somewhat OT: `krakenex` `v2.0.0` should be released this week; it's using `requests`, and has much more consistent error reporting. For now, the release candidate `v2.0.0c2` is available.

**Comment by Newbrict** [comment]
Looking forward to v2 then :)

**Comment by veox** [comment]
`v2.0.0` has been pushed out, and is available on PyPI (meaning also via `pip install`).

OK to close?..

**Comment by Newbrict** [comment]
Yes thank you
